import React, { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, Circle, Clock3, LockKeyhole, Play, RefreshCw, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { api, errorMessage } from "../lib/api";
import { buildJourneyStages, currentStageWork } from "../constants/caseJourney";

const canInitialize = user => ["admin", "administrator", "professional", "manager"].includes(String(user?.role || "").toLowerCase());
const formatDate = value => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "No statutory due date";
const stateIcon = state => state === "completed" ? <CheckCircle2 size={18} /> : state === "blocked" ? <ShieldAlert size={18} /> : state === "current" ? <Clock3 size={18} /> : <Circle size={18} />;

export default function CaseJourneyWorkspace({ caseRecord, user, onNavigate }) {
  const [workflow, setWorkflow] = useState(null); const [summary, setSummary] = useState(null);
  const [selected, setSelected] = useState("admission"); const [loading, setLoading] = useState(true); const [missing, setMissing] = useState(false); const [busy, setBusy] = useState("");
  const load = async () => { setLoading(true); try { const [workflowResponse, summaryResponse] = await Promise.all([api.get(`/cases/${caseRecord.id}/workflow`), api.get(`/cases/${caseRecord.id}/workflow/summary`)]); setWorkflow(workflowResponse.data); setSummary(summaryResponse.data); setMissing(false); } catch (error) { if (error.response?.status === 404) setMissing(true); else toast.error(errorMessage(error, "Could not load the CIRP Journey.")); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [caseRecord.id]);
  const stages = useMemo(() => buildJourneyStages(workflow?.steps || []), [workflow]);
  const selectedStage = stages.find(stage => stage.id === selected) || stages.find(stage => ["current", "blocked"].includes(stage.state)) || stages[0];
  const currentStage = stages.find(stage => ["current", "blocked"].includes(stage.state));
  const runStep = async (step, action) => { const endpoint = action === "start" ? "start" : action; const payload = action === "block" || action === "waive" ? { reason: window.prompt(`Reason to ${action} this step:`) || "" } : action === "complete" ? { remarks: window.prompt("Completion remarks (optional):") || "" } : {}; if (["block", "waive"].includes(action) && !payload.reason) return; setBusy(`${step.id}:${action}`); try { await api.post(`/cases/${caseRecord.id}/workflow/steps/${step.id}/${endpoint}`, payload); toast.success(`Workflow step ${action}ed`); load(); } catch (error) { toast.error(errorMessage(error, `Could not ${action} this workflow step.`)); } finally { setBusy(""); } };
  const assignStep = async step => { const owner_user_id = window.prompt("Owner user ID (leave blank to clear):") || null; const checker_user_id = window.prompt("Checker user ID (leave blank to clear):") || null; setBusy(`${step.id}:assignment`); try { await api.patch(`/cases/${caseRecord.id}/workflow/steps/${step.id}/assignment`, { owner_user_id, checker_user_id, priority: step.priority || "NORMAL" }); toast.success("Workflow ownership updated"); load(); } catch (error) { toast.error(errorMessage(error, "Could not update workflow ownership.")); } finally { setBusy(""); } };
  const attachEvidence = async step => { const evidence_type = window.prompt("Evidence type required by this step:"); if (!evidence_type) return; const document_id = window.prompt("Case document ID to attach:"); if (!document_id) return; setBusy(`${step.id}:evidence`); try { await api.post(`/cases/${caseRecord.id}/workflow/steps/${step.id}/evidence`, { evidence_type, document_id, source_type: "document", source_id: document_id }); toast.success("Evidence attached"); load(); } catch (error) { toast.error(errorMessage(error, "Could not attach workflow evidence.")); } finally { setBusy(""); } };
  const overrideDeadline = async step => { const due_date = window.prompt("Replacement statutory due date (YYYY-MM-DD):", step.effective_due_date || ""); if (!due_date) return; const reason = window.prompt("Reason for the deadline override:"); if (!reason) return; setBusy(`${step.id}:deadline`); try { await api.post(`/cases/${caseRecord.id}/workflow/steps/${step.id}/deadline-override`, { due_date, reason }); toast.success("Deadline override recorded"); load(); } catch (error) { toast.error(errorMessage(error, "Could not override this deadline.")); } finally { setBusy(""); } };
  const initialize = async () => { if (!window.confirm("Initialize the versioned CIRP Journey for this case? This creates the approved workflow records.")) return; setBusy("initialize"); try { await api.post(`/cases/${caseRecord.id}/workflow/initialize`, {}); toast.success("CIRP Journey initialized"); load(); } catch (error) { toast.error(errorMessage(error, "Could not initialize the CIRP Journey.")); } finally { setBusy(""); } };
  if (loading) return <section className="journey-loading"><RefreshCw size={18} /> Loading the CIRP Journey…</section>;
  if (missing) return <section className="journey-setup casefile-panel" data-testid="journey-setup"><LockKeyhole size={25} /><div><p className="kicker">WORKFLOW SETUP REQUIRED</p><h3>This older case does not yet have a CIRP Journey</h3><p>Opening this case never creates legal workflow records. An authorised user must explicitly initialize the approved workflow version.</p>{canInitialize(user) ? <button className="primary-button" onClick={initialize} disabled={busy === "initialize"}>{busy === "initialize" ? "Initializing…" : "Initialize CIRP Journey"}</button> : <p className="journey-note">Ask an administrator, manager or professional user to initialize this case.</p>}</div></section>;
  const work = currentStageWork(selectedStage);
  return <div className="case-journey" data-testid="case-journey"><section className="journey-banner"><div><p className="kicker">CIRP JOURNEY · VERSIONED WORKFLOW</p><h3>{currentStage ? `${currentStage.title} is the current legal stage` : "CIRP Journey progress"}</h3><p>{summary?.completed_steps || 0} of {summary?.total_steps || workflow?.steps?.length || 0} workflow steps terminal. Case master “current stage” is display metadata only.</p></div><div className="journey-progress"><b>{summary?.progress_percentage ?? Math.round((stages.reduce((sum, stage) => sum + stage.terminalCount, 0) / Math.max(1, stages.reduce((sum, stage) => sum + stage.totalCount, 0))) * 100)}%</b><span>workflow complete</span></div></section>
    <section className="journey-timeline" aria-label="CIRP Journey stages">{stages.map((stage, index) => <button key={stage.id} onClick={() => setSelected(stage.id)} className={`journey-stage ${stage.state} ${selectedStage?.id === stage.id ? "selected" : ""}`} data-testid={`journey-stage-${stage.id}`}><span className="journey-stage-number">{index + 1}</span><span className="journey-stage-icon">{stateIcon(stage.state)}</span><span className="journey-stage-copy"><b>{stage.title}</b><small>{stage.complete ? "All applicable steps terminal" : `${stage.activeSteps.length} active action${stage.activeSteps.length === 1 ? "" : "s"}`}</small><small>{formatDate(stage.nextDue)}</small></span><span className="journey-stage-progress">{stage.progress}%</span><ChevronRight size={16} /></button>)}</section>
    <section className="journey-detail casefile-panel"><header><div><p className="kicker">{selectedStage.state === "upcoming" ? "UPCOMING REQUIREMENTS" : "WHAT NEEDS ATTENTION NOW"}</p><h3>{selectedStage.title}</h3><p>{selectedStage.description}</p></div><span className={`journey-state ${selectedStage.state}`}>{selectedStage.state}</span></header>
      {selectedStage.state === "upcoming" ? <div className="journey-upcoming"><p>This stage is not ready work yet. Its requirements are shown for planning only; ordinary future tasks are intentionally excluded from today’s worklist.</p><ol>{selectedStage.steps.map(step => <li key={step.id}><b>{step.step_code}</b> — {step.activity || step.standard_output || "Workflow requirement"}</li>)}</ol></div> : <div className="journey-worklist">{work.map(step => <article key={step.id} className={step.status === "BLOCKED" ? "blocked" : ""}><div><b>{step.step_code} · {step.activity || step.standard_output}</b><small>{step.status.replaceAll("_", " ")} · Due {formatDate(step.effective_due_date)}</small>{step.task_title && <small>Linked task: {step.task_title} ({step.task_status || "open"})</small>}{step.evidence_status === "MISSING" && <small className="warning"><AlertTriangle size={13} /> Mandatory evidence missing</small>}{step.approval_status && step.approval_status !== "NOT_REQUIRED" && <small>Approval: {step.approval_status.replaceAll("_", " ")}</small>}</div><div className="journey-step-actions">{step.status === "READY" && <button className="outline-button small" disabled={Boolean(busy)} onClick={() => runStep(step, "start")}><Play size={14} />Start</button>}{["IN_PROGRESS", "WAITING", "BLOCKED"].includes(step.status) && <button className="outline-button small" disabled={Boolean(busy)} onClick={() => runStep(step, "complete")}>Complete</button>}{step.status === "PENDING_APPROVAL" && <button className="outline-button small" disabled={Boolean(busy)} onClick={() => runStep(step, "approve")}>Approve</button>}<button className="text-button" disabled={Boolean(busy)} onClick={() => assignStep(step)}>Assign</button><button className="text-button" disabled={Boolean(busy)} onClick={() => attachEvidence(step)}>Evidence</button><button className="text-button" disabled={Boolean(busy)} onClick={() => overrideDeadline(step)}>Deadline</button><button className="text-button" disabled={Boolean(busy)} onClick={() => runStep(step, "block")}>Block</button><button className="text-button" disabled={Boolean(busy)} onClick={() => runStep(step, "waive")}>Waive</button></div></article>)}{!work.length && <p className="panel-empty">No active workflow actions in this stage. Review the linked workspace or completed record history.</p>}</div>}
      <footer className="journey-destinations">{selectedStage.destinations.map(([id, label]) => <button key={id} className="outline-button" onClick={() => onNavigate(id)}>{label}<ChevronRight size={15} /></button>)}</footer></section>
  </div>;
}
