import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Download, FilePlus2, Plus, RefreshCw, Search } from "lucide-react";
import { toast } from "sonner";
import { api, API_BASE, errorMessage } from "../lib/api";

const categories = ["FINANCIAL_CREDITOR", "OPERATIONAL_CREDITOR", "WORKMAN_EMPLOYEE", "GOVERNMENT_AUTHORITY", "OTHER_CREDITOR"];
const forms = ["Form B", "Form C", "Form CA", "Form D", "Form E", "Form F", "Other"];
const statuses = ["RECEIVED", "UNDER_VERIFICATION", "INFORMATION_REQUIRED", "RESPONSE_RECEIVED", "ADMITTED", "PARTLY_ADMITTED", "REJECTED", "WITHDRAWN"];
const documentTypes = ["Claim Form", "Invoice", "Ledger", "Agreement", "Loan Agreement", "Sanction Letter", "Bank Statement", "Interest Calculation", "Security Document", "Charge Document", "Court Order", "Correspondence", "GST / Tax Document", "Other"];
const label = value => String(value || "—").replaceAll("_", " ").replace(/\b\w/g, character => character.toUpperCase());
const money = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value || 0));
const today = () => new Date().toISOString().slice(0, 10);
const blankClaim = { received_date: today(), creditor_name: "", creditor_category: "", form_type: "", claimed_amount: "", email: "", contact_person: "", phone: "", received_via: "Email", related_party_status: "UNKNOWN", currency: "INR", principal_claimed: "", interest_claimed: "", other_amount_claimed: "", sender_email: "", sender_name: "", email_subject: "", source_notes: "" };

function Metric({ name, value, moneyValue }) {
  return <div className="claim-metric"><span>{name}</span><b>{moneyValue ? money(value) : value || 0}</b></div>;
}

function ClaimIntake({ caseId, onCreated, onCancel }) {
  const [form, setForm] = useState(blankClaim);
  const [file, setFile] = useState(null);
  const [documentType, setDocumentType] = useState("Claim Form");
  const [busy, setBusy] = useState(false);
  const componentTotal = [form.principal_claimed, form.interest_claimed, form.other_amount_claimed].reduce((sum, value) => sum + Number(value || 0), 0);
  const hasComponents = [form.principal_claimed, form.interest_claimed, form.other_amount_claimed].some(value => value !== "");
  const mismatch = hasComponents && Math.abs(componentTotal - Number(form.claimed_amount || 0)) >= 0.01;
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const submit = async event => {
    event.preventDefault();
    if (!file) return toast.error("Attach the original claim document before saving.");
    setBusy(true);
    try {
      const idempotencyKey = globalThis.crypto?.randomUUID?.() || `${Date.now()}-${file.name}`;
      const { data: claim } = await api.post(`/cases/${caseId}/claims`, { ...form, idempotency_key: idempotencyKey });
      const upload = new FormData(); upload.append("file", file); upload.append("document_type", documentType);
      await api.post(`/cases/${caseId}/claims/${claim.id}/documents/upload`, upload);
      toast.success(`${claim.claim_number} created with its original document`); onCreated(claim.id);
    } catch (error) { toast.error(errorMessage(error, "Could not create the claim.")); }
    finally { setBusy(false); }
  };
  return <form className="casefile-panel claim-intake" onSubmit={submit} data-testid="claim-intake-form">
    <div className="panel-heading"><div><p className="kicker">QUICK MANUAL INTAKE</p><h3>Add new claim</h3><p className="module-description">Capture the received claim first. Verification details can be completed later.</p></div><button type="button" className="text-button" onClick={onCancel}>Cancel</button></div>
    <div className="form-grid">
      <label>Date received<input type="date" required value={form.received_date} onChange={e => set("received_date", e.target.value)} /></label>
      <label>Received via<select value={form.received_via} onChange={e => set("received_via", e.target.value)}>{["Email", "Physical", "Portal", "Other"].map(item => <option key={item}>{item}</option>)}</select></label>
      <label className="full">Creditor name<input required value={form.creditor_name} onChange={e => set("creditor_name", e.target.value)} /></label>
      <label>Creditor category<select required value={form.creditor_category} onChange={e => set("creditor_category", e.target.value)}><option value="">Select category</option>{categories.map(item => <option key={item} value={item}>{label(item)}</option>)}</select></label>
      <label>Claim form/type<select required value={form.form_type} onChange={e => set("form_type", e.target.value)}><option value="">Select form</option>{forms.map(item => <option key={item}>{item}</option>)}</select></label>
      <label>Total amount claimed (INR)<input type="number" min="0" step="0.01" required value={form.claimed_amount} onChange={e => set("claimed_amount", e.target.value)} /></label>
      <label>Email/contact<input required value={form.email} onChange={e => set("email", e.target.value)} placeholder="Email or office contact" /></label>
      <details className="full claim-optional"><summary>Amount components and optional receipt details</summary><div className="form-grid">
        <label>Principal claimed<input type="number" min="0" step="0.01" value={form.principal_claimed} onChange={e => set("principal_claimed", e.target.value)} /></label>
        <label>Interest claimed<input type="number" min="0" step="0.01" value={form.interest_claimed} onChange={e => set("interest_claimed", e.target.value)} /></label>
        <label>Other amount claimed<input type="number" min="0" step="0.01" value={form.other_amount_claimed} onChange={e => set("other_amount_claimed", e.target.value)} /></label>
        <label>Calculated component total<input value={money(componentTotal)} readOnly /></label>
        <label>Contact person<input value={form.contact_person} onChange={e => set("contact_person", e.target.value)} /></label>
        <label>Phone<input value={form.phone} onChange={e => set("phone", e.target.value)} /></label>
        <label>Sender email<input type="email" value={form.sender_email} onChange={e => set("sender_email", e.target.value)} /></label>
        <label>Sender name<input value={form.sender_name} onChange={e => set("sender_name", e.target.value)} /></label>
        <label className="full">Email subject<input value={form.email_subject} onChange={e => set("email_subject", e.target.value)} /></label>
        <label className="full">Email / source notes<textarea value={form.source_notes} onChange={e => set("source_notes", e.target.value)} /></label>
      </div></details>
      {mismatch && <div className="claim-warning full">CLAIM TOTAL DOES NOT MATCH COMPONENTS — stated {money(form.claimed_amount)}, calculated {money(componentTotal)}. The stated total will be preserved.</div>}
      <label>Document category<select value={documentType} onChange={e => setDocumentType(e.target.value)}>{documentTypes.map(item => <option key={item}>{item}</option>)}</select></label>
      <label>Original claim attachment<input type="file" required onChange={e => setFile(e.target.files?.[0] || null)} /></label>
    </div>
    <div className="modal-actions"><button className="primary-button" disabled={busy}><Check size={15} />{busy ? "Saving…" : "Save claim and document"}</button></div>
  </form>;
}

function DocumentsTab({ caseId, claim, reload, readOnly }) {
  const [file, setFile] = useState(null); const [documentType, setDocumentType] = useState("Other");
  const [newItem, setNewItem] = useState("");
  const upload = async event => { event.preventDefault(); if (!file) return; const body = new FormData(); body.append("file", file); body.append("document_type", documentType); try { await api.post(`/cases/${caseId}/claims/${claim.id}/documents/upload`, body); toast.success("Document linked to this claim"); setFile(null); reload(); } catch (error) { toast.error(errorMessage(error)); } };
  const updateChecklist = async (item, status) => { try { await api.put(`/cases/${caseId}/claims/${claim.id}/checklist/${item.id}`, { ...item, status }); reload(); } catch (error) { toast.error(errorMessage(error)); } };
  const addChecklist = async event => { event.preventDefault(); if (!newItem.trim()) return; try { await api.post(`/cases/${caseId}/claims/${claim.id}/checklist`, { label: newItem, status: "MISSING" }); setNewItem(""); reload(); } catch (error) { toast.error(errorMessage(error)); } };
  return <div className="claim-tab-stack"><section><h4>Claim documents</h4>{!readOnly && <form className="claim-upload" onSubmit={upload}><select value={documentType} onChange={e => setDocumentType(e.target.value)}>{documentTypes.map(item => <option key={item}>{item}</option>)}</select><input type="file" required onChange={e => setFile(e.target.files?.[0] || null)} /><button className="outline-button small"><FilePlus2 size={15} />Upload</button></form>}<div className="claim-document-list">{claim.documents.map(item => <a key={item.id} href={`${API_BASE}/cases/${caseId}/documents/${item.id}/file`} onClick={event => { event.preventDefault(); api.get(`/cases/${caseId}/documents/${item.id}/file`, { responseType: "blob" }).then(response => { const url = URL.createObjectURL(response.data); const anchor = document.createElement("a"); anchor.href = url; anchor.download = item.name; anchor.click(); URL.revokeObjectURL(url); }); }}><b>{item.name}</b><small>{item.category} · {new Date(item.created_at).toLocaleString()}</small></a>)}{!claim.documents.length && <p className="panel-empty">No documents linked.</p>}</div></section>
    <section><h4>Verification checklist</h4><div className="claim-checklist">{claim.checklist.map(item => <div key={item.id}><span>{item.label}</span><select disabled={readOnly} value={item.status} onChange={e => updateChecklist(item, e.target.value)}><option value="RECEIVED">Received</option><option value="MISSING">Missing</option><option value="NOT_APPLICABLE">N.A.</option></select></div>)}</div>{!readOnly && <form className="claim-checklist-add" onSubmit={addChecklist}><input placeholder="Add another required document" value={newItem} onChange={e => setNewItem(e.target.value)} /><button className="outline-button small">Add checklist item</button></form>}</section></div>;
}

function OverviewTab({ caseId, claim, reload, readOnly }) {
  const keys = ["contact_person", "email", "phone", "address", "date_debt_incurred", "due_date", "default_date", "interest_rate", "interest_basis", "security_details", "security_value", "charge_details", "source_notes"];
  const [form, setForm] = useState(Object.fromEntries(keys.map(key => [key, claim[key] ?? ""])));
  const save = async event => { event.preventDefault(); try { await api.put(`/cases/${caseId}/claims/${claim.id}`, form); reload(); toast.success("Claim details updated"); } catch (error) { toast.error(errorMessage(error)); } };
  return <div className="claim-overview"><dl><div><dt>Date received</dt><dd>{claim.received_date}</dd></div><div><dt>Received via</dt><dd>{claim.received_via}</dd></div><div><dt>Form</dt><dd>{claim.form_type}</dd></div><div><dt>Related party</dt><dd>{label(claim.related_party_status)}</dd></div><div><dt>Security</dt><dd>{label(claim.secured_status)}</dd></div><div><dt>Claimed</dt><dd>{money(claim.claimed_amount)}</dd></div><div><dt>Admitted</dt><dd>{money(claim.admitted_amount)}</dd></div><div><dt>Not admitted</dt><dd>{money(claim.amount_not_admitted)}</dd></div><div><dt>Currency</dt><dd>{claim.currency}</dd></div></dl>
    <form className="claim-overview-edit" onSubmit={save}><h4>Creditor, debt and security details</h4><div className="form-grid"><label>Contact person<input disabled={readOnly} value={form.contact_person} onChange={e => setForm({ ...form, contact_person: e.target.value })} /></label><label>Email<input disabled={readOnly} value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Phone<input disabled={readOnly} value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label className="full">Address<textarea disabled={readOnly} value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /></label><label>Debt incurred<input disabled={readOnly} type="date" value={form.date_debt_incurred} onChange={e => setForm({ ...form, date_debt_incurred: e.target.value })} /></label><label>Due date<input disabled={readOnly} type="date" value={form.due_date} onChange={e => setForm({ ...form, due_date: e.target.value })} /></label><label>Default date<input disabled={readOnly} type="date" value={form.default_date} onChange={e => setForm({ ...form, default_date: e.target.value })} /></label><label>Interest rate (%)<input disabled={readOnly} type="number" min="0" step="0.01" value={form.interest_rate} onChange={e => setForm({ ...form, interest_rate: e.target.value })} /></label><label className="full">Interest basis / remarks<textarea disabled={readOnly} value={form.interest_basis} onChange={e => setForm({ ...form, interest_basis: e.target.value })} /></label><label className="full">Security description<textarea disabled={readOnly} value={form.security_details} onChange={e => setForm({ ...form, security_details: e.target.value })} /></label><label>Security value<input disabled={readOnly} type="number" min="0" step="0.01" value={form.security_value} onChange={e => setForm({ ...form, security_value: e.target.value })} /></label><label className="full">Charge details<textarea disabled={readOnly} value={form.charge_details} onChange={e => setForm({ ...form, charge_details: e.target.value })} /></label><label className="full">Email / source notes<textarea disabled={readOnly} value={form.source_notes} onChange={e => setForm({ ...form, source_notes: e.target.value })} /></label></div>{!readOnly && <button className="primary-button">Save details</button>}</form>
  </div>;
}

function VerificationTab({ caseId, claim, reload, readOnly }) {
  const [form, setForm] = useState({ decision_status: "ADMITTED", principal_admitted: claim.principal_claimed || 0, interest_admitted: claim.interest_claimed || 0, other_amount_admitted: claim.other_amount_claimed || 0, admitted_amount: claim.claimed_amount, decision_date: today(), reason: "", verification_notes: claim.verification_notes || "", issues_identified: claim.issues_identified || "", documents_checked: claim.documents_checked || "", related_party_status: claim.related_party_status, secured_status: claim.secured_status, override_reason: "" });
  const total = Number(form.principal_admitted || 0) + Number(form.interest_admitted || 0) + Number(form.other_amount_admitted || 0);
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const start = async () => { try { await api.post(`/cases/${caseId}/claims/${claim.id}/verification/start`); reload(); toast.success("Verification started"); } catch (error) { toast.error(errorMessage(error)); } };
  const decide = async event => { event.preventDefault(); try { await api.post(`/cases/${caseId}/claims/${claim.id}/decision`, { ...form, admitted_amount: total }); reload(); toast.success("Claim decision recorded with history"); } catch (error) { toast.error(errorMessage(error)); } };
  return <div className="verification-layout"><section className="claim-side creditor"><p className="kicker">WHAT CREDITOR CLAIMED</p><dl><div><dt>Principal</dt><dd>{claim.principal_claimed == null ? "Not split" : money(claim.principal_claimed)}</dd></div><div><dt>Interest</dt><dd>{claim.interest_claimed == null ? "Not split" : money(claim.interest_claimed)}</dd></div><div><dt>Other</dt><dd>{claim.other_amount_claimed == null ? "Not split" : money(claim.other_amount_claimed)}</dd></div><div className="total"><dt>Stated total</dt><dd>{money(claim.claimed_amount)}</dd></div></dl>{claim.total_mismatch && <div className="claim-warning">Claim total does not match components.</div>}</section>
    <form className="claim-side" onSubmit={decide}><p className="kicker">RP VERIFICATION / ADMISSION</p>{claim.status === "RECEIVED" && !readOnly && <button type="button" className="outline-button small" onClick={start}>Start verification</button>}<div className="form-grid">
      <label>Verified principal<input disabled={readOnly} type="number" min="0" step="0.01" value={form.principal_admitted} onChange={e => set("principal_admitted", e.target.value)} /></label><label>Verified interest<input disabled={readOnly} type="number" min="0" step="0.01" value={form.interest_admitted} onChange={e => set("interest_admitted", e.target.value)} /></label><label>Verified other<input disabled={readOnly} type="number" min="0" step="0.01" value={form.other_amount_admitted} onChange={e => set("other_amount_admitted", e.target.value)} /></label><label>Calculated admitted total<input value={money(total)} readOnly /></label>
      <label>Decision<select disabled={readOnly} value={form.decision_status} onChange={e => set("decision_status", e.target.value)}><option value="ADMITTED">Admitted</option><option value="PARTLY_ADMITTED">Partly admitted</option><option value="REJECTED">Rejected</option></select></label><label>Decision date<input disabled={readOnly} type="date" value={form.decision_date} onChange={e => set("decision_date", e.target.value)} /></label>
      <label>Related-party conclusion<select disabled={readOnly} value={form.related_party_status} onChange={e => set("related_party_status", e.target.value)}>{["UNKNOWN", "YES", "NO"].map(item => <option key={item}>{item}</option>)}</select></label><label>Security conclusion<select disabled={readOnly} value={form.secured_status} onChange={e => set("secured_status", e.target.value)}>{["UNKNOWN", "SECURED", "UNSECURED", "PARTLY_SECURED", "NOT_APPLICABLE"].map(item => <option key={item}>{label(item)}</option>)}</select></label>
      <label className="full">Documents checked<textarea disabled={readOnly} value={form.documents_checked} onChange={e => set("documents_checked", e.target.value)} /></label><label className="full">Issues identified<textarea disabled={readOnly} value={form.issues_identified} onChange={e => set("issues_identified", e.target.value)} /></label><label className="full">Verification notes<textarea disabled={readOnly} value={form.verification_notes} onChange={e => set("verification_notes", e.target.value)} /></label>
      {(form.decision_status === "PARTLY_ADMITTED" || form.decision_status === "REJECTED") && <label className="full">Decision reason (required)<textarea disabled={readOnly} required value={form.reason} onChange={e => set("reason", e.target.value)} /></label>}
      <label className="full">Override reason (only when decision conflicts with normal amount rules)<textarea disabled={readOnly} value={form.override_reason} onChange={e => set("override_reason", e.target.value)} /></label>
    </div>{!readOnly && <button className="primary-button">Record decision</button>}</form></div>;
}

function QueriesTab({ caseId, claim, reload, readOnly }) {
  const [templates, setTemplates] = useState([]); const [form, setForm] = useState({ query_date: today(), subject: "", query_text: "", information_requested: "", sent_to: claim.email || "", response_due_date: "", status: "SENT" });
  const [response, setResponse] = useState({ queryId: "", response_received_date: today(), response_notes: "", source_reference: "", query_status: "RESPONDED", document_ids: [] });
  useEffect(() => { api.get(`/cases/${caseId}/claims/query-templates`).then(({ data }) => setTemplates(data)).catch(() => {}); }, [caseId]);
  const chooseTemplate = key => { const item = templates.find(entry => entry.key === key); if (item) setForm(current => ({ ...current, subject: item.subject, query_text: item.text, information_requested: item.subject })); };
  const create = async event => { event.preventDefault(); try { await api.post(`/cases/${caseId}/claims/${claim.id}/queries`, form); reload(); toast.success("Query recorded"); } catch (error) { toast.error(errorMessage(error)); } };
  const record = async event => { event.preventDefault(); try { await api.post(`/cases/${caseId}/claims/${claim.id}/queries/${response.queryId}/responses`, response); reload(); toast.success("Response recorded"); } catch (error) { toast.error(errorMessage(error)); } };
  return <div className="claim-query-grid">{!readOnly && <form onSubmit={create}><h4>Raise query</h4><label>Standard wording<select onChange={e => chooseTemplate(e.target.value)} defaultValue=""><option value="">Select optional template</option>{templates.map(item => <option key={item.key} value={item.key}>{item.subject}</option>)}</select></label><label>Query date<input type="date" value={form.query_date} onChange={e => setForm({ ...form, query_date: e.target.value })} /></label><label>Subject<input required value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} /></label><label>Final editable query text<textarea required value={form.query_text} onChange={e => setForm({ ...form, query_text: e.target.value })} /></label><label>Information/documents requested<textarea value={form.information_requested} onChange={e => setForm({ ...form, information_requested: e.target.value })} /></label><label>Send to<input value={form.sent_to} onChange={e => setForm({ ...form, sent_to: e.target.value })} /></label><label>Response due<input type="date" value={form.response_due_date} onChange={e => setForm({ ...form, response_due_date: e.target.value })} /></label><button className="primary-button">Save query</button></form>}
    <section><h4>Query history</h4>{claim.queries.map(query => <article className="query-card" key={query.id}><b>{query.subject}</b><span className="status-chip">{label(query.status)}</span><p>{query.query_text}</p><small>{query.query_date} · to {query.sent_to || "not recorded"}</small>{query.responses.map(item => <div className="query-response" key={item.id}><b>Response {item.response_received_date}</b><p>{item.response_notes || "No response note"}</p><small>{item.source_reference}</small></div>)}</article>)}{!claim.queries.length && <p className="panel-empty">No queries raised.</p>}{!readOnly && claim.queries.length > 0 && <form className="response-form" onSubmit={record}><h4>Record response</h4><select required value={response.queryId} onChange={e => setResponse({ ...response, queryId: e.target.value })}><option value="">Select query</option>{claim.queries.map(item => <option key={item.id} value={item.id}>{item.subject}</option>)}</select><input type="date" value={response.response_received_date} onChange={e => setResponse({ ...response, response_received_date: e.target.value })} /><textarea placeholder="Response notes" value={response.response_notes} onChange={e => setResponse({ ...response, response_notes: e.target.value })} /><input placeholder="Email/source reference" value={response.source_reference} onChange={e => setResponse({ ...response, source_reference: e.target.value })} />{claim.documents.length > 0 && <label>Documents received<select multiple value={response.document_ids} onChange={e => setResponse({ ...response, document_ids: Array.from(e.target.selectedOptions, option => option.value) })}>{claim.documents.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<button className="outline-button">Record response</button></form>}</section></div>;
}

function HistoryTab({ caseId, claim, reload, readOnly }) {
  const [revision, setRevision] = useState({ reason: "", claimed_amount: claim.claimed_amount, principal_claimed: claim.principal_claimed ?? "", interest_claimed: claim.interest_claimed ?? "", other_amount_claimed: claim.other_amount_claimed ?? "" });
  const revise = async event => { event.preventDefault(); try { await api.post(`/cases/${caseId}/claims/${claim.id}/revisions`, { reason: revision.reason, changes: { claimed_amount: revision.claimed_amount, principal_claimed: revision.principal_claimed, interest_claimed: revision.interest_claimed, other_amount_claimed: revision.other_amount_claimed } }); reload(); toast.success("New claim revision preserved"); } catch (error) { toast.error(errorMessage(error)); } };
  return <div className="history-layout"><section><h4>Business timeline</h4><div className="claim-timeline">{claim.history.map(item => <div key={item.id}><time>{new Date(item.occurred_at).toLocaleString()}</time><b>{item.title}</b><small>{label(item.event_type)}</small></div>)}</div></section><section><h4>Versions and decisions</h4>{claim.revisions.map(item => <div className="version-row" key={item.id}><b>Claim version {item.revision}</b><span>{item.reason}</span><small>{new Date(item.created_at).toLocaleString()}</small></div>)}{claim.decisions.map(item => <div className="version-row decision" key={item.id}><b>{label(item.decision_status)} · {money(item.admitted_amount)}</b><span>{item.reason || "No reason required"}</span><small>{item.decision_date}</small></div>)}{!readOnly && <form className="revision-form" onSubmit={revise}><h4>Record revised claim</h4><input required placeholder="Why is the claim being revised?" value={revision.reason} onChange={e => setRevision({ ...revision, reason: e.target.value })} /><div className="form-grid"><label>Principal<input type="number" min="0" step="0.01" value={revision.principal_claimed} onChange={e => setRevision({ ...revision, principal_claimed: e.target.value })} /></label><label>Interest<input type="number" min="0" step="0.01" value={revision.interest_claimed} onChange={e => setRevision({ ...revision, interest_claimed: e.target.value })} /></label><label>Other<input type="number" min="0" step="0.01" value={revision.other_amount_claimed} onChange={e => setRevision({ ...revision, other_amount_claimed: e.target.value })} /></label><label>Revised total<input required type="number" min="0" step="0.01" value={revision.claimed_amount} onChange={e => setRevision({ ...revision, claimed_amount: e.target.value })} /></label></div><button className="outline-button">Create new version</button></form>}</section></div>;
}

function ClaimDetail({ caseId, claimId, onBack, readOnly }) {
  const [claim, setClaim] = useState(null); const [tab, setTab] = useState("overview");
  const load = useCallback(() => api.get(`/cases/${caseId}/claims/${claimId}`).then(({ data }) => setClaim(data)).catch(error => toast.error(errorMessage(error))), [caseId, claimId]);
  useEffect(() => { load(); }, [load]);
  if (!claim) return <div className="casefile-panel panel-empty">Loading claim…</div>;
  const tabs = ["overview", "documents", "verification", "queries", "history"];
  return <section className="casefile-panel claim-detail"><div className="claim-detail-head"><button className="icon-btn" onClick={onBack}><ArrowLeft size={17} /></button><div><p className="kicker">{claim.claim_number} · VERSION {claim.revision}</p><h3>{claim.creditor_name}</h3><p>{label(claim.creditor_category)} · {money(claim.claimed_amount)}</p></div><span className="status-chip">{label(claim.status)}</span></div><nav className="claim-detail-tabs">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{label(item)}</button>)}</nav>
    {tab === "overview" && <OverviewTab caseId={caseId} claim={claim} reload={load} readOnly={readOnly} />}
    {tab === "documents" && <DocumentsTab caseId={caseId} claim={claim} reload={load} readOnly={readOnly} />}{tab === "verification" && <VerificationTab caseId={caseId} claim={claim} reload={load} readOnly={readOnly} />}{tab === "queries" && <QueriesTab caseId={caseId} claim={claim} reload={load} readOnly={readOnly} />}{tab === "history" && <HistoryTab caseId={caseId} claim={claim} reload={load} readOnly={readOnly} />}
  </section>;
}

function CreditorsList({ caseId, onBack }) {
  const [rows, setRows] = useState([]); useEffect(() => { api.get(`/cases/${caseId}/claims/list-of-creditors`).then(({ data }) => setRows(data)); }, [caseId]);
  const download = async () => { try { const response = await api.get(`/cases/${caseId}/claims/list-of-creditors/export/docx`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "List of Creditors.docx"; anchor.click(); URL.revokeObjectURL(url); } catch (error) { toast.error(errorMessage(error)); } };
  return <section className="casefile-panel"><div className="panel-heading"><div className="claim-heading-back"><button className="icon-btn" onClick={onBack}><ArrowLeft size={17} /></button><div><p className="kicker">DERIVED FROM CLAIMS</p><h3>List of Creditors</h3></div></div><button className="primary-button" onClick={download}><Download size={15} />Export DOCX</button></div><div className="module-table-wrap"><table className="module-table"><thead><tr><th>Creditor</th><th>Category</th><th>Claimed</th><th>Admitted</th><th>Not admitted</th><th>Security</th><th>Decision</th></tr></thead><tbody>{rows.map(row => <tr key={row.claim_id}><td><b>{row.creditor}</b><small>{row.claim_number}</small></td><td>{label(row.category)}</td><td>{money(row.amount_claimed)}</td><td>{money(row.amount_admitted)}</td><td>{money(row.amount_not_admitted)}</td><td>{label(row.security_status)}</td><td><span className="status-chip">{label(row.decision_status)}</span></td></tr>)}</tbody></table></div></section>;
}

export default function ClaimsWorkspace({ caseRecord }) {
  const caseId = caseRecord.id; const [claims, setClaims] = useState([]); const [summary, setSummary] = useState({ categories: {}, statuses: {} }); const [selected, setSelected] = useState(null); const [creating, setCreating] = useState(false); const [creditors, setCreditors] = useState(false); const [readOnly, setReadOnly] = useState(false); const [filters, setFilters] = useState({ status: "", category: "", dateFrom: "", dateTo: "", search: "" });
  const load = useCallback(async () => { try { const [items, totals, me] = await Promise.all([api.get(`/cases/${caseId}/claims`), api.get(`/cases/${caseId}/claims/summary`), api.get("/auth/me")]); setClaims(items.data); setSummary(totals.data); setReadOnly(["viewer", "read-only"].includes(me.data.role)); } catch (error) { toast.error(errorMessage(error, "Could not load claims.")); } }, [caseId]);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => claims.filter(item => (!filters.status || item.status === filters.status) && (!filters.category || item.creditor_category === filters.category) && (!filters.dateFrom || item.received_date >= filters.dateFrom) && (!filters.dateTo || item.received_date <= filters.dateTo) && (!filters.search || `${item.creditor_name} ${item.claim_number} ${item.email}`.toLowerCase().includes(filters.search.toLowerCase()))), [claims, filters]);
  if (selected) return <ClaimDetail caseId={caseId} claimId={selected} onBack={() => { setSelected(null); load(); }} readOnly={readOnly} />;
  if (creditors) return <CreditorsList caseId={caseId} onBack={() => setCreditors(false)} />;
  return <div className="claims-workspace space-y-6"><div className="claim-summary-grid"><Metric name="Claims received" value={summary.total_claims} /><Metric name="Total claimed" value={summary.total_claimed} moneyValue /><Metric name="Total admitted" value={summary.total_admitted} moneyValue /><Metric name="Under verification" value={summary.statuses?.UNDER_VERIFICATION} /><Metric name="Information required" value={summary.statuses?.INFORMATION_REQUIRED} /><Metric name="Partly admitted" value={summary.statuses?.PARTLY_ADMITTED} /></div>
    {creating && <ClaimIntake caseId={caseId} onCancel={() => setCreating(false)} onCreated={id => { setCreating(false); setSelected(id); }} />}
    <section className="casefile-panel"><div className="panel-heading"><div><p className="kicker">CASE-SPECIFIC REGISTER</p><h3>Claims Register</h3><p className="module-description">Creditor claims, verification, queries and admission decisions for {caseRecord.name}.</p></div><div className="flex gap-2"><button className="outline-button small" onClick={() => setCreditors(true)}>List of Creditors</button><button className="icon-btn" onClick={load}><RefreshCw size={16} /></button>{!readOnly && <button className="primary-button small" onClick={() => setCreating(true)}><Plus size={15} />Add New Claim</button>}</div></div>
      <div className="claim-filters"><label><Search size={14} /><input placeholder="Search creditor or claim no." value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })} /></label><select value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option>{statuses.map(item => <option key={item} value={item}>{label(item)}</option>)}</select><select value={filters.category} onChange={e => setFilters({ ...filters, category: e.target.value })}><option value="">All categories</option>{categories.map(item => <option key={item} value={item}>{label(item)}</option>)}</select><input type="date" title="Received from" value={filters.dateFrom} onChange={e => setFilters({ ...filters, dateFrom: e.target.value })} /><input type="date" title="Received to" value={filters.dateTo} onChange={e => setFilters({ ...filters, dateTo: e.target.value })} /></div>
      <div className="module-table-wrap"><table className="module-table claims-register"><thead><tr><th>Claim No.</th><th>Date Received</th><th>Creditor</th><th>Category</th><th>Form</th><th>Amount Claimed</th><th>Amount Admitted</th><th>Status</th><th>Last Action</th><th>Documents</th><th>Actions</th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><b>{item.claim_number}</b></td><td>{item.received_date}</td><td>{item.creditor_name}</td><td>{label(item.creditor_category)}</td><td>{item.form_type}</td><td>{money(item.claimed_amount)}</td><td>{money(item.admitted_amount)}</td><td><span className="status-chip">{label(item.status)}</span></td><td>{item.last_action || "Claim received"}</td><td>{item.document_count}</td><td><button className="text-button" onClick={() => setSelected(item.id)}>Open</button></td></tr>)}{!visible.length && <tr><td colSpan="11" className="panel-empty">No claims match these filters.</td></tr>}</tbody></table></div>
    </section></div>;
}
