import React, { useCallback, useEffect, useState } from "react";
import { Gavel, ListChecks, Vote } from "lucide-react";
import { toast } from "sonner";
import { api, errorMessage } from "../lib/api";

const loadMany = async (caseId, modules) => Promise.all(modules.map(module => api.get(`/cases/${caseId}/${module}`).then(response => response.data)));

export function OrdersAndDirections({ caseId }) {
  const [hearings, setHearings] = useState([]); const [applications, setApplications] = useState([]); const [orders, setOrders] = useState([]); const [directions, setDirections] = useState([]);
  const [order, setOrder] = useState({ order_date: "", summary: "", hearing_id: "", application_id: "" });
  const [direction, setDirection] = useState({ order_id: "", direction: "", due_date: "" });
  const load = useCallback(() => loadMany(caseId, ["hearings", "applications", "orders", "order-directions"]).then(([h, a, o, d]) => { setHearings(h); setApplications(a); setOrders(o); setDirections(d); }).catch(error => toast.error(errorMessage(error))), [caseId]);
  useEffect(() => { load(); }, [load]);
  const submit = async (module, payload, reset) => { try { await api.post(`/cases/${caseId}/${module}`, Object.fromEntries(Object.entries(payload).filter(([, value]) => value !== ""))); reset(); load(); toast.success("Linked record created"); } catch (error) { toast.error(errorMessage(error)); } };
  return <section className="casefile-panel"><div className="panel-heading"><div><p className="kicker">ORDERS & DIRECTIONS</p><h3>Tribunal outcomes</h3><p className="module-description">Every recorded direction automatically creates a linked task.</p></div><Gavel size={20} /></div><div className="grid grid-cols-1 xl:grid-cols-2 gap-6"><form className="linked-form" onSubmit={e => { e.preventDefault(); submit("orders", order, () => setOrder({ order_date: "", summary: "", hearing_id: "", application_id: "" })); }}><h4>Record order</h4><label>Order date<input type="date" required value={order.order_date} onChange={e => setOrder({ ...order, order_date: e.target.value })} /></label><label>Related hearing<select value={order.hearing_id} onChange={e => setOrder({ ...order, hearing_id: e.target.value })}><option value="">None</option>{hearings.map(item => <option key={item.id} value={item.id}>{item.hearing_at} · {item.purpose}</option>)}</select></label><label>Related application<select value={order.application_id} onChange={e => setOrder({ ...order, application_id: e.target.value })}><option value="">None</option>{applications.map(item => <option key={item.id} value={item.id}>{item.number || item.application_type}</option>)}</select></label><label>Summary<textarea value={order.summary} onChange={e => setOrder({ ...order, summary: e.target.value })} /></label><button className="outline-button">Save order</button></form><form className="linked-form" onSubmit={e => { e.preventDefault(); submit("order-directions", direction, () => setDirection({ order_id: "", direction: "", due_date: "" })); }}><h4>Record direction</h4><label>Order<select required value={direction.order_id} onChange={e => setDirection({ ...direction, order_id: e.target.value })}><option value="">Select order</option>{orders.map(item => <option key={item.id} value={item.id}>{item.order_date} · {item.summary || "Order"}</option>)}</select></label><label>Direction<textarea required value={direction.direction} onChange={e => setDirection({ ...direction, direction: e.target.value })} /></label><label>Due date<input type="date" value={direction.due_date} onChange={e => setDirection({ ...direction, due_date: e.target.value })} /></label><button className="outline-button">Create direction and task</button></form></div><div className="master-list">{directions.map(item => <div key={item.id}><b>{item.direction}</b><small>Due {item.due_date || "not set"} · {item.status} · task linked</small></div>)}</div></section>;
}

export function ClaimChecklist({ caseId }) {
  const [claims, setClaims] = useState([]); const [documents, setDocuments] = useState([]); const [form, setForm] = useState({ claim_id: "", name: "", required: true, received: false, notes: "" });
  const load = useCallback(() => loadMany(caseId, ["claims", "claim-documents"]).then(([a, b]) => { setClaims(a); setDocuments(b); }).catch(error => toast.error(errorMessage(error))), [caseId]);
  useEffect(() => { load(); }, [load]);
  const create = async event => { event.preventDefault(); try { await api.post(`/cases/${caseId}/claim-documents`, form); setForm({ claim_id: "", name: "", required: true, received: false, notes: "" }); load(); toast.success("Claim checklist item added"); } catch (error) { toast.error(errorMessage(error)); } };
  return <section className="casefile-panel"><div className="panel-heading"><div><p className="kicker">VERIFICATION CHECKLIST</p><h3>Claim supporting documents</h3></div><ListChecks size={20} /></div><form className="linked-inline-form" onSubmit={create}><select required value={form.claim_id} onChange={e => setForm({ ...form, claim_id: e.target.value })}><option value="">Select claim</option>{claims.map(item => <option key={item.id} value={item.id}>{item.creditor_category} · ₹{item.claimed_amount}</option>)}</select><input required placeholder="Required document" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><label><input type="checkbox" checked={form.received} onChange={e => setForm({ ...form, received: e.target.checked })} />Received</label><button className="outline-button">Add item</button></form><div className="master-list">{documents.map(item => <div key={item.id}><b>{item.name}</b><small>{item.received ? "Received" : "Pending"}{item.required ? " · required" : ""}</small></div>)}</div></section>;
}

export function CocVoting({ caseId }) {
  const [meetings, setMeetings] = useState([]); const [members, setMembers] = useState([]); const [votes, setVotes] = useState([]); const [form, setForm] = useState({ meeting_id: "", member_id: "", agenda_key: "", vote: "yes", voting_share: 0 });
  const load = useCallback(() => loadMany(caseId, ["coc-meetings", "coc-members", "coc-votes"]).then(([a, b, c]) => { setMeetings(a); setMembers(b); setVotes(c); }).catch(error => toast.error(errorMessage(error))), [caseId]);
  useEffect(() => { load(); }, [load]);
  const create = async event => { event.preventDefault(); try { await api.post(`/cases/${caseId}/coc-votes`, form); setForm({ meeting_id: "", member_id: "", agenda_key: "", vote: "yes", voting_share: 0 }); load(); toast.success("Vote recorded at its historical share"); } catch (error) { toast.error(errorMessage(error)); } };
  return <section className="casefile-panel"><div className="panel-heading"><div><p className="kicker">VOTING REGISTER</p><h3>CoC votes</h3></div><Vote size={20} /></div><form className="linked-inline-form" onSubmit={create}><select required value={form.meeting_id} onChange={e => setForm({ ...form, meeting_id: e.target.value })}><option value="">Meeting</option>{meetings.map(item => <option key={item.id} value={item.id}>Meeting {item.meeting_number}</option>)}</select><select required value={form.member_id} onChange={e => { const member = members.find(item => item.id === e.target.value); setForm({ ...form, member_id: e.target.value, voting_share: member?.voting_share || 0 }); }}><option value="">Member</option>{members.map(item => <option key={item.id} value={item.id}>{item.authorized_representative || "CoC member"} · {item.voting_share}%</option>)}</select><input required placeholder="Agenda item / resolution" value={form.agenda_key} onChange={e => setForm({ ...form, agenda_key: e.target.value })} /><select value={form.vote} onChange={e => setForm({ ...form, vote: e.target.value })}><option value="yes">Yes</option><option value="no">No</option><option value="abstain">Abstain</option></select><button className="outline-button">Record vote</button></form><div className="master-list">{votes.map(item => <div key={item.id}><b>{item.agenda_key}: {item.vote}</b><small>{item.voting_share}% voting share</small></div>)}</div></section>;
}
