import React, { useEffect, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { api, errorMessage } from "../lib/api";

const registers = [["engagements", "Engagements"], ["transaction_review_scopes", "Review scopes"], ["transaction_audit_document_requirements", "Document requirements"], ["transaction_bank_coverages", "Bank coverage"], ["transaction_related_parties", "Related parties"], ["transaction_audit_workstreams", "Workstreams"], ["transaction_audit_transactions", "Transactions"], ["transaction_audit_findings", "Findings"], ["transaction_avoidance_decisions", "Avoidance decisions"], ["transaction_avoidance_applications", "Applications"]];
const actionNames = ["engagement", "scope", "quotation_preview", "quotation_issue", "quotation_dispatch", "quotation_response", "auditor_select", "auditor_appoint", "document_requirement", "document_requirement_status", "bank_coverage", "bank_coverage_update", "related_party", "related_party_confirm", "workstream", "workstream_complete", "transaction", "finding", "finding_finalize", "finding_party", "source_index", "finding_evidence", "report_version", "finding_rp_review", "finding_legal_review", "avoidance_decision", "avoidance_application", "avoidance_application_update"];
const pretty = value => String(value || "").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

export default function TransactionAuditWorkspace({ caseRecord }) {
  const [register, setRegister] = useState("engagements"), [records, setRecords] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ action: "engagement", payload: '{\n  "remarks": ""\n}' });
  const load = async () => { setLoading(true); try { const { data } = await api.get(`/cases/${caseRecord.id}/transaction-audit/${register}`); setRecords(Array.isArray(data) ? data : data.records || []); } catch (error) { toast.error(errorMessage(error, "Could not load the transaction-audit register.")); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [register, caseRecord.id]);
  const submit = async event => { event.preventDefault(); let payload; try { payload = JSON.parse(form.payload); } catch { toast.error("Action details must be valid JSON."); return; } setBusy(true); try { await api.post(`/cases/${caseRecord.id}/transaction-audit/actions/${form.action}`, payload); toast.success(`${pretty(form.action)} recorded`); load(); } catch (error) { toast.error(errorMessage(error, "Could not complete this transaction-audit action.")); } finally { setBusy(false); } };
  return <div className="operator-workspace" data-testid="transaction-audit-workspace"><section className="operator-banner"><div><p className="kicker">CIRP-077 TO CIRP-084</p><h3>Transaction audit & avoidance</h3><p>Use the existing controlled actions and registers for engagement, evidence, findings, professional review and applications.</p></div><button className="outline-button" onClick={load}><RefreshCw size={15} />Refresh</button></section><div className="operator-layout"><aside><p className="kicker">REGISTERS</p>{registers.map(([id, label]) => <button key={id} className={register === id ? "active" : ""} onClick={() => setRegister(id)}>{label}</button>)}</aside><main><section className="casefile-panel"><div className="panel-heading"><div><p className="kicker">CONTROLLED ACTION</p><h3>Record transaction audit work</h3></div></div><form onSubmit={submit} className="form-grid"><label>Action<select value={form.action} onChange={event => setForm({ ...form, action: event.target.value })}>{actionNames.map(action => <option key={action} value={action}>{pretty(action)}</option>)}</select></label><label className="full">Action details (JSON)<textarea value={form.payload} onChange={event => setForm({ ...form, payload: event.target.value })} /><small>Required fields depend on the selected controlled action. The server validates all references, case isolation and professional confirmation.</small></label><button className="primary-button" disabled={busy}><Plus size={16} />{busy ? "Recording…" : "Run action"}</button></form></section><section className="casefile-panel"><div className="panel-heading"><div><p className="kicker">{pretty(register)}</p><h3>{records.length} record{records.length === 1 ? "" : "s"}</h3></div></div>{loading ? <p className="panel-empty">Loading register…</p> : <div className="operator-records">{records.map(record => <details key={record.id}><summary><b>{record.status || record.review_type || "Record"}</b><span>{record.created_at?.slice(0, 10) || ""}</span></summary><pre>{JSON.stringify(record, null, 2)}</pre></details>)}{!records.length && <p className="panel-empty">No records in this register.</p>}</div>}</section></main></div></div>;
}
