import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { FileText, LayoutDashboard, Settings, Clock3, Plus, Download, ArrowRight, Search, CheckCircle2, ChevronLeft } from "lucide-react";
import { toast, Toaster } from "sonner";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

function App() {
  const [view, setView] = useState("workspace");
  const [templates, setTemplates] = useState([]);
  const [documents, setDocuments] = useState([]);
  const [selected, setSelected] = useState(null);
  const [step, setStep] = useState(1);
  const [values, setValues] = useState({});
  const [notes, setNotes] = useState("");
  const [query, setQuery] = useState("");
  useEffect(() => { Promise.all([axios.get(`${API}/templates`), axios.get(`${API}/documents`)]).then(([t, d]) => { setTemplates(t.data); setDocuments(d.data); }).catch(() => toast.error("Could not connect to the workspace")); }, []);
  const filtered = useMemo(() => templates.filter(t => `${t.name} ${t.category}`.toLowerCase().includes(query.toLowerCase())), [templates, query]);
  const start = template => { setSelected(template); setValues({}); setNotes(""); setStep(2); setView("new"); };
  const generate = async () => { try { const { data } = await axios.post(`${API}/documents`, { template_id: selected.id, values, notes }); setDocuments([data, ...documents]); setSelected({ ...selected, generated: data }); setStep(3); toast.success("Document ready to export"); } catch (e) { toast.error(e.response?.data?.detail || "Please complete the required fields"); } };
  const download = format => window.open(`${API}/documents/${selected.generated.id}/download/${format}`, "_blank");
  const nav = [{ id: "workspace", label: "Workspace", icon: LayoutDashboard }, { id: "templates", label: "Templates", icon: FileText }, { id: "recent", label: "Recent documents", icon: Clock3 }, { id: "settings", label: "Settings", icon: Settings }];
  return <div className="app-shell"><aside className="rail"><div className="brand"><span className="brand-mark">N</span><div><strong>Casefile</strong><small>NCLT WORKSPACE</small></div></div><div className="rail-rule" /><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} data-testid={`nav-${id}-button`} className={view === id ? "nav-item active" : "nav-item"} onClick={() => setView(id)}><Icon size={17} />{label}</button>)}</nav><button className="new-button" data-testid="new-document-button" onClick={() => { setView("templates"); setStep(1); }}><Plus size={17} />New document</button><div className="rail-footer"><span className="avatar">AK</span><div><b>Arun Kumar</b><small>Chartered Accountant</small></div></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">DOCUMENT OPERATIONS / 01</p><h1 data-testid="page-title">{view === "new" ? "New document" : view === "templates" ? "Template library" : view === "recent" ? "Recent documents" : "Workspace"}</h1></div><div className="top-status"><span className="status-dot" />All changes saved</div></header>{view === "new" ? <Generator selected={selected} step={step} setStep={setStep} values={values} setValues={setValues} notes={notes} setNotes={setNotes} onGenerate={generate} onBack={() => setView("templates")} onDownload={download} /> : <Workspace view={view} templates={filtered} documents={documents} query={query} setQuery={setQuery} onStart={start} onNew={() => setView("templates")} setView={setView} />}</main><Toaster position="bottom-right" /></div>;
}

function Workspace({ view, templates, documents, query, setQuery, onStart, onNew, setView }) { return <section className="workspace"><div className="workspace-intro"><div><p className="kicker">{view === "workspace" ? "GOOD MORNING, ARUN" : "YOUR LIBRARY"}</p><h2>{view === "workspace" ? "Keep your casework moving." : view === "templates" ? "Start from a trusted format." : view === "recent" ? "Your generated documents." : "Workspace preferences."}</h2><p className="intro-copy">{view === "workspace" ? "Turn familiar NCLT and insolvency formats into finished documents in minutes." : "Fixed templates, clear inputs, and export-ready files."}</p></div>{view !== "settings" && <button className="primary-button" data-testid="workspace-new-document-button" onClick={onNew}><Plus size={17} />New document <ArrowRight size={16} /></button>}</div>{view === "settings" ? <div className="settings-panel"><p className="kicker">ACCOUNT</p><h3>Workspace settings</h3><p>Template uploads and firm details will live here once your first samples are added.</p></div> : view === "recent" ? <Recent documents={documents} /> : <><div className="section-heading"><div><p className="kicker">{view === "workspace" ? "QUICK START" : "AVAILABLE FORMATS"}</p><h3>Templates</h3></div><label className="search"><Search size={16} /><input data-testid="template-search-input" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search templates" /></label></div><div className="template-grid">{templates.map(t => <TemplateCard key={t.id} template={t} onStart={onStart} />)}</div>{view === "workspace" && <div className="recent-strip"><div className="section-heading"><div><p className="kicker">ACTIVITY</p><h3>Recent documents</h3></div><button className="text-button" data-testid="view-recent-button" onClick={() => setView("recent")}>View all <ArrowRight size={15} /></button></div><Recent documents={documents.slice(0, 3)} /></div>}</>}</section> }

function TemplateCard({ template, onStart }) { return <article className="template-card"><div className="doc-thumb"><span>CASEFILE</span><strong>{template.name.split(" ").slice(0, 2).join(" ")}</strong><i>{template.category}</i></div><div className="template-info"><span className="category-tag">{template.category}</span><h4>{template.name}</h4><p>{template.description}</p><button className="outline-button" data-testid={`use-template-${template.id}-button`} onClick={() => onStart(template)}>Use template <ArrowRight size={15} /></button></div></article> }

function Recent({ documents }) { return <div className="recent-list">{documents.length ? documents.map(d => <div className="recent-row" key={d.id} data-testid={`recent-document-${d.id}`}><div className="file-icon"><FileText size={18} /></div><div><b>{d.company_name}</b><span>{d.template_name} · {new Date(d.created_at).toLocaleDateString()}</span></div><em><CheckCircle2 size={14} />{d.status}</em></div>) : <div className="empty-state"><FileText size={24} /><b>No generated documents yet</b><span>Choose a template to create your first case document.</span></div>}</div> }

function Generator({ selected, step, values, setValues, notes, setNotes, onGenerate, onBack, onDownload }) { const groups = [...new Set(selected.fields.map(f => f.section))]; const missing = selected.fields.filter(f => f.required && !values[f.key]); return <section className="generator"><div className="stepper">{[[1, "Template"], [2, "Case details"], [3, "Review & export"]].map(([n, label]) => <div className={step === n ? "step active" : step > n ? "step done" : "step"} key={n}><span>{step > n ? "✓" : `0${n}`}</span>{label}</div>)}</div><div className="generator-head"><button className="back-button" data-testid="generator-back-button" onClick={onBack}><ChevronLeft size={18} />Templates</button><div><p className="kicker">{selected.category}</p><h2>{selected.name}</h2></div></div>{step === 2 && <div className="form-workspace"><form className="case-form" onSubmit={e => { e.preventDefault(); onGenerate(); }}>{groups.map(group => <fieldset key={group}><legend>{group}</legend>{selected.fields.filter(f => f.section === group).map(field => <label key={field.key} data-testid={`field-${field.key}-label`}>{field.label}{field.required && <span className="required">Required</span>}<input data-testid={`field-${field.key}-input`} required={field.required} value={values[field.key] || ""} placeholder={field.placeholder} onChange={e => setValues({ ...values, [field.key]: e.target.value })} /></label>)}</fieldset>)}<label className="notes-label">Additional notes <span>Optional</span><textarea data-testid="additional-notes-input" value={notes} onChange={e => setNotes(e.target.value)} placeholder="Add any matter-specific notes to include at the end..." /></label><div className="form-footer"><span>{missing.length ? `${missing.length} required ${missing.length === 1 ? "field" : "fields"} remaining` : "All required fields complete"}</span><button className="primary-button" data-testid="generate-document-button" type="submit">Generate document <ArrowRight size={16} /></button></div></form><Preview selected={selected} values={values} /></div>}{step === 3 && <div className="export-state"><div className="success-mark"><CheckCircle2 size={32} /></div><p className="kicker">READY TO FILE</p><h2>{selected.generated.company_name}</h2><p>Your {selected.generated.template_name} is ready. Download an editable Word copy or a print-ready PDF.</p><div className="export-actions"><button className="primary-button" data-testid="download-word-button" onClick={() => onDownload("docx")}><Download size={17} />Download Word</button><button className="outline-button" data-testid="download-pdf-button" onClick={() => onDownload("pdf")}><Download size={17} />Download PDF</button></div><button className="text-button" data-testid="create-another-button" onClick={onBack}>Create another document <ArrowRight size={15} /></button></div>}</section> }

function Preview({ selected, values }) { return <div className="preview-wrap"><div className="preview-label"><span>LIVE PREVIEW</span><small>{selected.fields.filter(f => values[f.key]).length}/{selected.fields.length} fields</small></div><div className="paper-preview" data-testid="document-preview"><p className="paper-eyebrow">BEFORE THE NATIONAL COMPANY LAW TRIBUNAL</p><h3>{selected.name.toUpperCase()}</h3><hr />{selected.fields.slice(0, 5).map(f => <p key={f.key}><b>{f.label}</b><span className={values[f.key] ? "filled" : "blank"}>{values[f.key] || "Awaiting input"}</span></p>)}<div className="paper-line" /><small>Preview updates as you complete the case details.</small></div></div> }

export default App;